@startuml

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title Dependency Tree

frame Application{
    card program
}

frame Core{
'0.
    card Door
    card Button
    card Timer

'1.
    card UserInterface

'2.
    card CookController
    card Light

'3.
    card PowerTube
    card Display

'4 
    card Output


}
Application -- Core

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
UserInterface -- CookController
UserInterface -- CookController
'1. to 2.
'Door - CookController

Timer -- CookController 
Timer -- CookController

CookController -- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -- Light
CookController -- Display


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml