@startuml IT03-Sut

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title IT01 Sut 3

'0.
    card Door<<tested>>
    card Button<<tested>>
    card Timer<<tested>>

'1.
    card UserInterface<<tested>>

'2.
    card CookController<<tested>>
    card Light<<tested>>

'3.
    card PowerTube<<sut>>
    card Display<<sut>>

'4 
    card Output

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
UserInterface -- CookController
UserInterface -- CookController
'1. to 3.
'Door - CookController

Timer -- CookController 
Timer -- CookController 

CookController -[thickness=2]- PowerTube

'1. to 2.
UserInterface -[thickness=2]- Display
UserInterface -- Light
CookController -[thickness=2]- Display


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml