@startuml

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title It01 Sut

frame Application{
    card program
}

frame Core{
    card UserInterface<<tested>>
    card CookController<<fake>>

    card Door<<test>>
    card Light<<test>>
    card Timer
    card PowerTube
    card Display<<test>>
    card Output<<fake>>
    card Button<<fake>>
}

'Relations projects
' 0. to 1.
Application -- Core

'Relations CookController:
'1.
CookController - UserInterface
'1. to 2.
CookController -- Door
CookController -- Timer
CookController -- PowerTube
CookController -- Display

'Relations UserInterface:
'1.
UserInterface - CookController
Button - UserInterface 
UserInterface - Button

'1. to 2.
UserInterface -- Light
UserInterface -- Door
UserInterface -- Display


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml