@startuml IT02-Sut

'Testing colors:
skinparam card {
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title IT01 Sut 2

frame Application {
    card program
}

frame Core {
'0.
    card Door<<tested>>
    card Button<<tested>>
    card Timer<<tested>>

'1.
    card UserInterface<<tested>>

'2.
    card CookController<<sut>>
    card Light<<sut>>

'3.
    card PowerTube
    card Display

'4 
    card Output

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
UserInterface -[thickness=2]- CookController
UserInterface -[thickness=2]- CookController

'1. to 3.
'Door -[thickness=2]- CookController

Timer -- CookController
Timer -- CookController


CookController -- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -[thickness=2]- Light
CookController -- Display



' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml