@startuml sut03

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<under-test>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

'0.
    card Door<<tested>>
    card Button<<tested>>
    card Timer<<tested>>

'1.
    card UserInterface<<tested>>

'2.
    card Light<<tested>>
frame sut04{
    card CookController<<tested>>

'3.
    card PowerTube<<under-test>>
}
    card Display

'4 
    card Output

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
UserInterface -- CookController
UserInterface -- CookController
'1. to 3.
'Door - CookController

Timer -- CookController 
Timer -- CookController 

CookController -[thickness=3]- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -- Light
CookController -- Display


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml