@startuml sut02

'Testing colors:
skinparam card {
    backgroundColor<<tested>> lawngreen
    backgroundColor<<under-test>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}


'0.
    card Door<<tested>>
    card Button<<tested>>
    card Timer<<tested>>

'1.
frame sut02{
    card UserInterface<<tested>>

'2.
    card Light<<under-test>>
}
    card CookController

'3.
    card PowerTube
    card Display

'4 
    card Output

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
UserInterface -- CookController
UserInterface -- CookController

'1. to 3.
'Door -[thickness=2]- CookController

Timer -- CookController
Timer -- CookController


CookController -- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -[thickness=3]- Light
CookController -- Display



' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output

@enduml