@startuml

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title It01 Sut

frame Application{
    card program
}

frame Core{
    card UserInterface
    card CookController

    card Door
    card Light
    card Timer
    card PowerTube
    card Display
    card Output
    card Button
}
Application -- Core

'Relations projects
' 0. to 1.
Door -- UserInterface
Door -- UserInterface

Button -- UserInterface
Button -- UserInterface


'Relations CookController:
'1.
CookController - UserInterface
'1. to 2.
Door - CookController

Timer -- CookController
Timer -- CookController

CookController -- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -- Light
CookController -- Display


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml