@startuml IT01-Sut

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title IT01 Sut 1

'0.
    card Door<<tested>>
    card Button<<tested>>

'1.
    card UserInterface<<sut>>

'2.
    card CookController
    card Light

'3.
    card Timer
    card PowerTube
    card Display

'4 
    card Output


'Relations projects
' 0. to 1.
Door -[thickness=2]- UserInterface
Door -[thickness=2]- UserInterface

Button -[thickness=2]- UserInterface
Button -[thickness=2]- UserInterface


'Relations CookController:
'1.
UserInterface -- CookController
UserInterface -- CookController
'1. to 2.
Door -- CookController


CookController -- PowerTube

'1. to 2.
UserInterface -- Display
UserInterface -- Light
CookController -- Display

CookController -- Timer
CookController -- Timer 


' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml