@startuml

'Testing colors:
skinparam card{
    backgroundColor<<tested>> lawngreen
    backgroundColor<<sut>> salmon
    backgroundColor<<test>> salmon
    backgroundColor<<fake>> gold
}

header SWT group 8
title It03 Sut

frame Application{
    card program
}

frame Core{
    card UserInterface<<tested>>
    card CookController<<tested>>

    card Door<<tested>>
    card Light<<tested>>
    card Timer<<tested>>
    card PowerTube<<tested>>
    card Display<<tested>>
    card Output<<fake>>
    card Button<<tested>>
}

'Relations projects
' 0. to 1.
Application -- Core

'Relations CookController:
'1.
CookController - UserInterface
'1. to 2.
CookController -- Door
CookController -- Timer
CookController -- PowerTube
CookController -- Display

'Relations UserInterface:
'1.
UserInterface - CookController
Button - UserInterface 
UserInterface - Button

'1. to 2.
UserInterface -- Light
UserInterface -- Door
UserInterface -- Display

' Relations 2. to 3.
Light -- Output
Display -- Output
PowerTube -- Output



@enduml