
@startuml

card program        

card Door
card Light
card Timer
card Output 
card PowerTube
card Display
card Button

card UserInterface
card CookController



'Relations:
'program --> controller


@enduml